name = "chatterbox-local-scribe"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[env.production]
name = "chatterbox-local-scribe-production"

[env.preview]
name = "chatterbox-local-scribe-preview" 